<a href="https://colab.research.google.com/github/Amishi111/Capg-training/blob/main/Data-Analytics/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#syntax for array creation
var=np.array((1,2,3,{1:1,2:2}))
var.dtype

dtype('O')

In [3]:
#upcasting
fi = np.array((True,3,2.3,2+6j,'string',{0,1},{1:2}))
fi

array([True, 3, 2.3, (2+6j), 'string', {0, 1}, {1: 2}], dtype=object)

In [4]:
#vectorization
arr = np.array([1,2,3,4,5])
arr-1  #doesn't store just performs
arr*4
arr/2
arr//2
arr**2
arr%2

array([1, 0, 1, 0, 1])

In [5]:
#broadcasting
a1=np.array([1,2,3])
a2=np.array([4,5])
#a1+a2

In [6]:
#properties
dt=np.array([1,2,3,3.5])
#1
dt.dtype   #returns the datatype of the values of the array
#2
dt.shape   #displays (row,columns) dimensions of an array as a tuple
#3
dt.ndim    #returns the dimension of an array as an integer
#4
dt.size    #length of the array i.e. number of elements
#5
dt.itemsize  #returns the size of each element of the array in bytes

8

In [7]:
d2 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
d2.shape
d2.size

9

In [8]:
d3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],

              [[1,2,3],
              [4,5,6],
              [7,8,9]]])
d3.shape
d3.size   #in case of 3d array it is the multiplication of all values in shape i.e. (2*3*3) in this case

18

In [9]:
d4=np.array([[[[1,2,3],
              [4,5,6],
              [7,8,9]],

              [[1,2,3],
              [4,5,6],
              [7,8,9]]],

            [[[1,2,3],
              [4,5,6],
              [7,8,9]],

              [[1,2,3],
              [4,5,6],
              [7,8,9]]]])
d4.size

36

In [10]:
#indexing
s=np.array([1,2,3])
s[-1]      #array supports indexing
d2[2,-1]
d3[0,1] #first array's second row
d3[0,1,2] #first array's second row's third element

np.int64(6)

In [11]:
d3+d2  #broadcasting of different dimensions
#internal shapes should be same i.e. if (2,4,3) and (3,3) are added it will throw an error because the 4th row cannot be logically added to d2

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

In [12]:
#slicing
#coll[si:ei:]
d1=np.array([1,2,3,4,5])
d1[2:4:1]
d1[2:4]
d1[::-1][1:3]
d2[0][1:]
d2[1][1:]
d2[1:]
d2[2:]
d2[1:,2]
d2[1:,1:]

array([[5, 6],
       [8, 9]])

In [13]:
d3
d3[0,1:,1:]
d3[1,1:,1:]
d3[1][1:,1:]
d3[:,:,2] #last column of both the 2D arrays
d3[1:,:,:] #first 2D array
d3[1:,:,2] #last column of first 2D array
d3[1:,:,1:] #second 2D array


array([[[2, 3],
        [5, 6],
        [8, 9]]])

In [14]:
d3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
dd = np.array([[[0, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [16]:
d3 * dd

array([[[ 0,  4,  9],
        [16, 25, 36],
        [49, 64, 81]],

       [[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]]])

In [17]:
range(10)
np.arange(10)
np.arange(1,11,0.1)

array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,
        2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,
        3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,
        4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,
        5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,
        6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,
        7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,
        8.7,  8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,
        9.8,  9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8,
       10.9])

In [18]:
zeros = np.array(np.zeros((3,3)))
zeros

np.zeros(8)    #gives an array of zeros
np.ones((5,5))  #needs two parenthesis - gives an array of ones
np.full((3,3),5) #gives an array with the specified value
#np.linspace(start_value, end_value, value)
np.linspace(2,5,5) #linear space
np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.random.rand(3,3)

array([[0.44449537, 0.39753152, 0.00722186],
       [0.15613033, 0.6155801 , 0.45517967],
       [0.23131557, 0.72131338, 0.60811139]])

In [19]:
#statistical functions
np.sum(d1)
d1.size
np.var(d1)
np.std(d1)
np.median(d1)
t=np.arange(1,7)
np.median(t)
t.std
t.reshape((2,3))
t.reshape(-1)

array([1, 2, 3, 4, 5, 6])

#Practice Questions for Python

In [20]:
l=[10,20,35,50,75,80,85]
for i in l:
  for j in l:
    if j!=i and i+j==70:
        r={i,j}
print(list(r))

[50, 20]


In [21]:
def find_sum(arr,k):
  left=0
  right=len(arr)-1
  total=0
  while left<right:
    total = arr[left]+arr[right]
    if total == k:
      return arr[left],arr[right]
    elif total<k:
      left+=1
    else:
      right-=1
  return -1
arr=[10,20,35,50,75,80,85]
find_sum(arr,70)

(20, 50)

In [22]:
def max_sum_three_consecutive(arr):
    max_sum = float('-inf')
    current_sum = sum(arr[0:3])
    max_sum = current_sum
    result_indices = (0, 1, 2)

    for i in range(1, len(arr) - 2):
        current_sum = current_sum - arr[i-1] + arr[i+2]
        if current_sum > max_sum:
            max_sum = current_sum
            result_indices = (i, i+1, i+2)

    return max_sum, [arr[result_indices[0]], arr[result_indices[1]], arr[result_indices[2]]]

my_array = [5,2,-1,6,-2,7,3]
max_s, numbers = max_sum_three_consecutive(my_array)
print(f"The maximum sum of three consecutive numbers is: {max_s}")
print(f"The numbers are: {numbers}")

The maximum sum of three consecutive numbers is: 11
The numbers are: [6, -2, 7]


In [23]:
arr=[5,2,-1,6,-2,7,3]
def window(arr,k):
  left=0
  right=0
  for right in range(len(arr)):
    total+=arr[right]
    while total>k:
      total-=arr[left]
      left+=1
    if total==k:
      return True
  return False